name: git-action-full
run-name: ${{ github.actor }}
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: use nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.1'
      
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:${{ github.sha }}
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'


  deploy-to-production:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code 
        uses: actions/checkout@v5
      
      - name: copy docker-compose to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASSWORD}}
          source: "docker-compose.yml"
          target: "~/NODEJSCI/"

      - name: deploy via sss
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{ secrets.SSH_PASSWORD}}
          script: |
            export IMAGE_TAG=${{ github.sha }}
            cd ~/NODEJSCI
            docker compose pull
            docker compose up -d 